### ISSUE TITLE
vietnam gso data question

### ISSUE THREAD

**Issue by justinelliotmeyers** [ThangLeQuoc/vietnamese-provinces-database#14]
hey!
can you assist me with a question I have about terms of use for data from the gso for Vietnam? I've sent them several emails and no response. Perhaps you know?

Thank you!
Justin

**Comment by ThangLeQuoc** [comment]
Hi @justinelliotmeyers , I didn't find any email that could be the one that you mentioned.
My email is: thanglequoc.it@gmail.com
Beside sending email, you may raise your question here directly, I'll help to answer them if any

**Comment by ThangLeQuoc** [comment]
This project is completely open source under [MIT license](https://github.com/ThangLeQuoc/vietnamese-provinces-database/blob/master/LICENSE)
