### ISSUE TITLE
Missing District 2 data and some more?

### ISSUE THREAD

**Issue by minhquan1313** [ThangLeQuoc/vietnamese-provinces-database#44]
I think the database is lack of District 2 (Quận 2) data. Am I wrong or you are missing some data?

**Comment by minhquan1313** [comment]
Sorry, haven't read Readme before open this issue, closed for now.

**Comment by ThangLeQuoc** [comment]
It's nice that you figured out yourself.
Yes, District 9, District 2 and Thu Duc District were merged into the Thu Duc city (code 769) under decree 1111/NQ-UBTVQH14
https://thuvienphapluat.vn/van-ban/Bo-may-hanh-chinh/Nghi-quyet-1111-NQ-UBTVQH14-2020-sap-xep-don-vi-hanh-chinh-cap-huyen-cap-xa-Ho-Chi-Minh-460049.aspx
