### ISSUE TITLE
Dữ liệu chưa update tới 2024

### ISSUE THREAD

**Issue by deverlex** [ThangLeQuoc/vietnamese-provinces-database#45]
Ví dụ: phường Tam Bình - thành phố Thủ Đức chưa có, mong bác update bản mới nhất.
Cảm ơn

**Comment by ThangLeQuoc** [comment]
Phường Tam Bình nằm trong bảng `wards` có mã là 26803, trực thuộc Thành phố Thủ Đức ấy bác.
<img width="1156" alt="image" src="https://github.com/ThangLeQuoc/vietnamese-provinces-database/assets/20574640/100043fe-dbc8-48ee-b0e5-559cf73a9975">

**Comment by deverlex** [comment]
Dạ, em thấy rồi, cảm ơn bác nhiều nha
