### ISSUE TITLE
Thiếu các Huyện không có Xã

### ISSUE THREAD

**Issue by haiau** [ThangLeQuoc/vietnamese-provinces-database#68]
Chào @ThangLeQuoc , 
Nước ta có 5 huyện không phân chia thành các đơn vị hành chính cấp xã, đều là các huyện đảo, gồm: Cồn Cỏ (Quảng Trị), Bạch Long Vĩ (Hải Phòng), Hoàng Sa (Đà Nẵng), Lý Sơn (Quảng Ngãi), Côn Đảo (Bà Rịa – Vũng Tàu).

Tôi không tìm thấy 5 huyện này trong DB.
Mong nhận được sự phản hồi từ bạn.
Chân thành cảm ơn.
Trân trọng.

**Comment by ThangLeQuoc** [comment]
Xin chào bạn @haiau , mình có kiểm tra lại thì đúng là có thiếu sót các đơn vị hành chính trên như bạn đề cập.
Đây là sai sót của mình khi chuyển đổi sang việc lấy dữ liệu từ API, có vẻ như mình đã gặp bug không sinh data cho các huyện không có xã như bạn đã chỉ ra. 

Mình sẽ sửa và cập nhật lại trong thời gian sớm nhất, chân thành cảm ơn bạn.
